<?php
/**
 * Project: curl-cmd-php
 *
 * @author Amado Martinez <amado@projectivemotion.com>
 */

if(!isset($argv))
    die("Run from command line.");

// copied this from doctrine's bin/doctrine.php
$autoload_files = array( __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php');

foreach($autoload_files as $autoload_file)
{
    if(!file_exists($autoload_file)) continue;
    require_once $autoload_file;
}
// end autoloader finder

$cmdstring = readline('Curl command line: ');
$output_file    =   readline("Output filename ( mycurl.php ): ");

if($cmdstring == '')
{
    $cmdstring = "curl 'http://posttestserver.com/post.php?dir=curl-cmd-php&q-destination=Paris%2C+France&destination-id=504261&as-shown=false&q-localised-check-in=18%2F02%2F2016&q-localised-check-out=19%2F02%2F2016&q-rooms=1&q-room-0-adults=2&q-room-0-children=0&page-name=HomePage' -H 'DNT: 1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8,es;q=0.6' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://www.hotels.com/' -H 'Cookie: h_darq=f; guid=8532c7cc-98e4-4f10-9e45-75ef2ea30be0; searchReturningUser=true; channel=DC; 30dlt=seo.hcom.mx.z.www.google.com.mx; propertyReturningUser=true; SSSC=3.G6248991744302678837.3|1963.1874:1975.18819:2032.19434:2037.19449:214.20653:2158.20678:2182.20825:2188.20897:2190.20924:2191.20926:2199.21122:2203.21149:2215.21268:2218.21285:2220.21293:2223.21301:2228.21327:2231.21345:2232.21349:2234.21360:2235.21369:2248.21471:2257.21558:2261.21628; SESSID=RS75X9-Aa18MUXN1QDyxLwsLjc.prod1-lpa-15; SSID=CACWXh1QAQQAAADi4LhWNYOCA-LguFYDAAAAAAAoSrFX_PrDVgCSjNUIAAV8VAAA_PrDVgEAtwcABYNJAAD8-sNWAQCXCAAHglIAAPz6w1YBANEIAAc2VAAA_PrDVgEAtAgAB09TAADi4LhWAwCMCAAFoVEAAPz6w1YBAJsIAAWdUgAA_PrDVgEArAgABS1TAAD-sNWAQCqCAAFJVMAAPz6w1YBAPAHAAXqSwAA_PrDVgEAuwgABXlTAAD8-sNWAQCOCAAHvFEAAOLguFYDALoIAAVwUwAA_PrDVgEArwgABTVTAAD8-sNWAQCGCAAFWVEAAPz6w1YBAMgIAAXfUwAA_PrDVgEA9QcABflLAAD8-sNWAQC4CAAFZVMAAPz6w1YBALcIAAVhUwAA_PrDVgEAYggABa1QAAD8-sNWAQCnCAAFFFMAAPz6w1YBAKsHAAdgSQAA4uC4VgMAjwgAB75RAADi4LhWAwBuCAAHxlAAAOLguFYDAF4IAAA; SSRT=SvzDVgIDAQ; homepage_search_data=QWJ1IERoYWJpLCBVbml0ZWQgQXJhYiBFbWlyYXRlcw..%2F%2F24%2F02%2F2016%2F%2F25%2F02%2F2016%2F%2F2%2F%2Fdd%2FMM%2Fyyyy%2F%2F1634727; mvthistory=eJxNVTmSXDEIvVGXWMSibMqJA085ce547uDDG3091FMd%2FCcEAh5La7xG%2Fb5ohR40V3J96fUlK%2BNlr7FIthYvHuPlj7Ytptz6i3keO1k848VbZNu8RLrY%2FdGSsrQt4sJi55qXTDrXbniElg5%2BZDoQEC%2BN2Raaun1UCLPwPFjXHOMxmkKlSWtOXMkyOj48ByxzBcdJhCvvJ7mxwk5C4QNfwpfxleebFdcTTBRRfqCv1HlupxwRLRrjvEiDtAHCysJPqMAWnSAN%2BCeadhXI%2FKXHE1EeV8SKF2gfgiBNQkl1HxgH2YeO7TnoqXLVkmRQV6wwghVGAbaQ4VOMAaIlHY52lkpXYg2ia0nK8spEXsoBDQFXaorrnZUGyNCE3zlmA28QXevCeGYSDHdHAOSbramIdU68YuhnMo43S%2Bbw5gOBemfplaU8QOKS5wq3rnDrLre0jmko0K85vEYTHGKXqph8bKtE3Y4FQGoEKEmG01Rcpd2BoYRTHpHNE4%2BEkIh67Lk4gNDReUT7cOktnHeyqYdy64S9cerF3HWXjXth8HgrMHWgzHYHnncTEwx3cz6G3Zks9O2Wuql9H96%2BhduM%2BSTAGyNvOTRvcEePRRGiWHty7hVTWG7y4q0Zgq1S6w%2FNx5MZQPgGOu1uhsKteZjeq3NCktrAGpxmqbU6GuDZKpq1C9oYtqbfhIqUrctr3RE%2B7IbnNU7NkmOA2fnObeHc%2FX7w3TwbtzK6j722enPihmfn%2Fi8QKDR7eycDUIP751AYcQaNK4yOLbA6OKQl9vYbBtsc7%2FrmKdCjkH64qqbiBlcyG9xZlDH7n8xGg%2BzmlnH%2F58LbheyBO0KsyOrVw4AwmlP4vPbv54%2Ffn39%2Fffz%2BPwP63WPjA%3D%3D%212161.0.0; s_cc=true; SSPV=IFEAAAAAAAAABQAAAAAAAAAAAAMAAAAAAAA; user=QSplbl9NWHxIQ09NX0xBVEFNIUIqVVNEIUoqNw..; asc=1; s_vi=[CS]v1|2B5C7072051D0983-400019092001A296[CE]; SSLB=1; AFFLB=A; s_fid=0E133BF5930473A5-31C615679FBF9693; s_sq=hotelsallprod%3D%2526pid%253Dhome%252520page%2526pidt%253D1%2526oid%253DSearch%2526oidt%253D3%2526ot%253DSUBMIT' -H 'Connection: keep-alive' --data 'postvar1=hello&postvar2=world' --compressed";
}

if($output_file == '')
{
    $output_file = 'mycurl.php';
}

echo "Using Command: $cmdstring\n";

$CurlCmd    =   new \projectivemotion\CurlCmdPhp();
$CurlCmd->setCmdLine($cmdstring);

$php_code   =   $CurlCmd->generateCode();

file_put_contents($output_file, "<" . "?php\n\n// generated by curl-cmd-php (http://github.com/projectivemotion/curl-cmd-php/)\n\n" . $php_code);

echo "\nPHP Code written to $output_file\n";

$do_test_file   =   readline("Test php file? [Y/n]: ");

if($do_test_file == 'Y' || $do_test_file == 'y')
{
    echo "Now testing $output_file\n";
    require $output_file;

    $content = getCurl(TRUE);

    echo "\n\n\nCurl Returned: \n\n$content\n\n";
}
