<?php
/**
 * Project: curl-cmd-php
 *
 * @author Amado Martinez <amado@projectivemotion.com>
 */

namespace projectivemotion;


class CurlCmdPhp
{
    protected $cmdLine  =   '';

    public function get_URL()
    {
        $m = preg_match("#curl '([^']*?)'#", $this->getCmdLine(), $match);
        $url = parse_url($match[1]);
        return $url;
    }

    public function get_GET($parsed_url)
    {
        parse_str($parsed_url['query'], $getvars);

//    print_r($url);
//    print_r($getvars);

        return $getvars;
    }

    public function get_POST()
    {
        $m = preg_match("#--data '([^']*?)'#", $this->getCmdLine(), $matches);

        if(!$m)
            return false;

        parse_str($matches[1], $post);

        return $post;
    }

    public function getCmdLine()
    {
        return $this->cmdLine;
    }

    public function setCmdLine($cmdLine)
    {
        $this->cmdLine = $cmdLine;
    }

    public function get_HEADERS()
    {
        $m = preg_match_all("#-H\s+'([^']*?)'#", $this->getCmdLine(), $matches);

        if(!$m)
                return false;

        return $matches[1];
    }

    public function generateCode()
    {
        $url    = $this->get_URL();
        $get    = $this->get_GET($url);
        $post   = $this->get_POST();
        $headers    =   $this->get_HEADERS();


        unset($url['query']);

        ob_start();
        /**    Generated by curl-cmd-php    **/
        echo <<<'NOWDOC'

    function getCurl($verbose = FALSE)
    {
NOWDOC;

        echo PHP_EOL, "\t\$url = ";
        var_export($url);

        echo ";", PHP_EOL, "\t\$get = ";
        var_export($get);

        echo ';';

        if($post) {
            echo PHP_EOL, "\t\$post = ";
            var_export($post);
            echo ';';
        }

        if($headers) {
            echo PHP_EOL, "\t\$headers = ";
            var_export($headers);
            echo ';';
        }

        echo <<<'NOWDOC'

        $url_string = sprintf("%s://%s%s%s", $url['scheme'], $url['host'], $url['path'], '?' . http_build_query($get));

        $curl   =   curl_init($url_string);

NOWDOC;

        if($headers) {
            echo <<<'NOWDOC'

        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

NOWDOC;
        }

        if($post)
        {
            echo <<<'NOWDOC'
            curl_setopt($curl, CURLOPT_POST, 1);
            curl_setopt($curl, CURLOPT_POSTFIELDS, $post);
NOWDOC;
        }


        // print execute code
        echo <<<'HERE'
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);

        if($verbose){
            curl_setopt($curl, CURLOPT_STDERR, fopen('php://output', 'w+'));
            curl_setopt($curl, CURLOPT_VERBOSE, 1);
        }

        $response = curl_exec($curl);

        curl_close($curl);

        return $response;

    }
HERE;

        $get = ob_get_clean();

        return $get;
    }
}